### ISSUE TITLE
question about python-cluster and python-scatter

### ISSUE THREAD

**Issue by gyc913** [benedekrozemberczki/SEAL-CI#1]
Hello, I failed to build python-cluster 1.2.4 and python-scatter 1.1.2 with pytorch 0.4.1

It seems that python-scatter 1.0.4 can fit pytorch 0.4.1 
However, I cant find proper verision for python-cluster 

Thank you!

**Comment by benedekrozemberczki** [comment]
I suppose that with other versions of those packages the model would still work.

**Comment by heyjiege** [comment]
您好，我在运行您的代码的时候报错 RuntimeError: index 145 is out of bounds for dimension 0 with size 1， 提示错误可能出现在node_features_1 = torch.nn.functional.relu(self.graph_convolution_1(features, edges))这一句处，涉及scatter.py。查了很久的资料，都没有解决。请问您知道是什么问题导致的吗？
